export const STICKERS = [
  {
    id: "sticker",
    assetUrl: "/stickers/sticker.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker1",
    assetUrl: "/stickers/sticker1.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker2",
    assetUrl: "/stickers/sticker2.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker3",
    assetUrl: "/stickers/sticker3.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker4",
    assetUrl: "/stickers/sticker4.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker5",
    assetUrl: "/stickers/sticker5.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker6",
    assetUrl: "/stickers/sticker6.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker7",
    assetUrl: "/stickers/sticker7.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker8",
    assetUrl: "/stickers/sticker8.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker9",
    assetUrl: "/stickers/sticker9.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker10",
    assetUrl: "/stickers/sticker10.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker11",
    assetUrl: "/stickers/sticker11.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker12",
    assetUrl: "/stickers/sticker12.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker13",
    assetUrl: "/stickers/sticker13.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker14",
    assetUrl: "/stickers/sticker14.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker15",
    assetUrl: "/stickers/sticker15.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker16",
    assetUrl: "/stickers/sticker16.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
  {
    id: "sticker17",
    assetUrl: "/stickers/sticker17.svg",
    defaultWidth: 20,
    defaultHeight: 20,
  },
];
